# Generated by Django 3.1.3 on 2020-12-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='last_name',
        ),
    ]
