# Generated by Django 3.1.3 on 2020-12-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_auto_20201228_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='add_email',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='add_info',
            field=models.TextField(blank=True, max_length=31, null=True),
        ),
    ]
