# Generated by Django 3.1.3 on 2021-03-18 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('name_ru', models.CharField(max_length=25, null=True)),
                ('name_en', models.CharField(max_length=25, null=True)),
                ('name_uz', models.CharField(max_length=25, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('description_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description_uz', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('menu_position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('body_ru', models.TextField(null=True)),
                ('body_en', models.TextField(null=True)),
                ('body_uz', models.TextField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('content_image', models.ImageField(upload_to='articles/')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Published')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
