# Generated by Django 3.1.3 on 2020-12-16 07:00

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import sitepages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('picture', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=''), upload_to=sitepages.models.banners_image_directory_path)),
                ('picture_uz', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=''), upload_to=sitepages.models.banners_image_directory_path)),
                ('picture_en', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=''), upload_to=sitepages.models.banners_image_directory_path)),
                ('url', models.URLField(blank=True, null=True)),
                ('url_cat', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=1)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SlideOfProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', models.CharField(blank=True, max_length=63, null=True)),
                ('text_2', models.CharField(blank=True, max_length=63, null=True)),
                ('text_3', models.CharField(blank=True, max_length=63, null=True)),
                ('link', models.CharField(max_length=63)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.productimage')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ConstructorOfProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('products_list_count', models.IntegerField(default=4)),
                ('status', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
