# Generated by Django 3.1.3 on 2020-12-29 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_auto_20201228_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_ru', models.CharField(max_length=128, null=True)),
                ('name_en', models.CharField(max_length=128, null=True)),
                ('name_uz', models.CharField(max_length=128, null=True)),
                ('method_key', models.CharField(max_length=128, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_ru', models.CharField(max_length=150, null=True)),
                ('name_en', models.CharField(max_length=150, null=True)),
                ('name_uz', models.CharField(max_length=150, null=True)),
                ('mini_description', models.TextField(blank=True, null=True)),
                ('mini_description_ru', models.TextField(blank=True, null=True)),
                ('mini_description_en', models.TextField(blank=True, null=True)),
                ('mini_description_uz', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
                ('period', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('min_order_cost', models.IntegerField(default=0)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.JSONField(blank=True, null=True)),
                ('price', models.PositiveSmallIntegerField()),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('type_of_selling', models.CharField(blank=True, choices=[('weight', 'Weight'), ('qty', 'Qty')], max_length=15)),
                ('total', models.PositiveSmallIntegerField()),
                ('date_of_creat', models.DateTimeField(auto_now_add=True)),
                ('date_of_delivery', models.DateTimeField(blank=True, null=True)),
                ('date_of_cancel', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('method_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.paymentmethods')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_selling', models.CharField(blank=True, choices=[('weight', 'Weight'), ('qty', 'Qty')], max_length=15)),
                ('total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_of_creat', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(default=0, max_length=31)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
