# Generated by Django 3.1.3 on 2020-12-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.CharField(default=0, max_length=31),
        ),
    ]
