# Generated by Django 3.1.3 on 2020-12-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='name_fr',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='name_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='name_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethods',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethods',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethods',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethods',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethods',
            name='mini_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethods',
            name='mini_description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethods',
            name='mini_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethods',
            name='mini_description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethods',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethods',
            name='name_fr',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethods',
            name='name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethods',
            name='name_uz',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
