# Generated by Django 3.1.3 on 2021-01-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201230_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='props',
            field=models.TextField(blank=True, null=True),
        ),
    ]
