# Generated by Django 3.1.3 on 2021-01-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_paymentmethods_props'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('paid', 'Paid')], default='waiting', max_length=15),
        ),
    ]
