# Generated by Django 3.1.3 on 2021-01-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('not_exists', 'Not Exists')], default='waiting', max_length=15),
        ),
    ]
