# Generated by Django 3.1.3 on 2020-11-19 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('slug', models.CharField(max_length=31)),
                ('image', models.ImageField(upload_to='category/')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(default=0, max_length=11)),
                ('status', models.IntegerField(choices=[(1, 'In Stock'), (0, 'Out Of Stock')], default=1)),
                ('sale', models.PositiveSmallIntegerField(default=0, help_text='Sale on percent')),
                ('min_weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_qty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sku', models.CharField(max_length=63)),
                ('date_of_created', models.DateTimeField(auto_now_add=True)),
                ('number_of_pieces', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=products.models.product_image_path)),
                ('type', models.IntegerField(choices=[(1, 'Productmainimage'), (2, 'Categorymainimage'), (3, 'Nutritionfacts')], default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
