# Generated by Django 3.1.3 on 2020-12-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201223_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_from_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='recipes_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status_uz',
        ),
    ]
