# Generated by Django 3.1.3 on 2020-12-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201223_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_for_qty',
        ),
        migrations.AddField(
            model_name='product',
            name='price_for_weight',
            field=models.CharField(default=0, max_length=11),
        ),
    ]
