# Generated by Django 3.1.3 on 2021-01-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201228_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=31, unique=True),
        ),
    ]
